version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ./backup/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - efk_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    networks:
      - efk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.3
    container_name: kibana
    volumes:
      - ./backup/kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - efk_network

networks:
  efk_network:
    driver: bridge
